[package]
name = "template"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { version = "0.84.0", features = ["oapi"] }
tokio = { version = "1.47.1", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
